### ISSUE TITLE
 Attempt to invoke virtual method 'void android.widget.RemoteViews.setTextViewText

### ISSUE THREAD

**Issue by gHashTag** [tlenclos/react-native-audio-streaming#105]
Why my app has stopping in Android emulator?

```
07-04 04:40:04.270 12583-12954/com.isk E/AndroidRuntime: FATAL EXCEPTION: Thread-10
                                                         Process: com.isk, PID: 12583
                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.RemoteViews.setTextViewText(int, java.lang.CharSequence)' on a null object reference
                                                             at com.audioStreaming.Signal.playerMetadata(Signal.java:333)
                                                             at com.spoledge.aacdecoder.IcyInputStream.parseMetadata(IcyInputStream.java:231)
                                                             at com.spoledge.aacdecoder.IcyInputStream.fetchMetadata(IcyInputStream.java:205)
                                                             at com.spoledge.aacdecoder.IcyInputStream.read(IcyInputStream.java:133)
                                                             at com.spoledge.aacdecoder.BufferReader.run(BufferReader.java:155)
                                                             at java.lang.Thread.run(Thread.java:764)
```
![bug mov](https://user-images.githubusercontent.com/6774813/27811895-7695c008-6073-11e7-9648-a0edbe820657.gif)

**Comment by cinder92** [comment]
+1

**Comment by gHashTag** [comment]
ReactNativeAudioStreaming.play(this.state.radioUrl, { showIniOSMediaCenter: true, showInAndroidNotifications: true})
All code:
https://gist.github.com/gHashTag/8470794d2cf6343dc58b9eab76c5b5a8
