### ISSUE TITLE
Why few audio links are not playing?

### ISSUE THREAD

**Issue by BhagyaSriPotnuru** [tlenclos/react-native-audio-streaming#106]
Following audio URLs are not playing:
1. http://www.geetganga.org/files/audio/Swamiji%20Vivekudu%20Kalalu%20Kanna%20Bharatam.mp3
2. http://www.geetganga.org/files/audio/hum_kare_rashtra_aradhan.mp3

07-04 15:26:10.849  29459-30445/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() frame decode error=1
07-04 15:26:10.849  29459-30445/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() first frame cannot be decoded - trying to sync again
07-04 15:26:10.850  29459-30445/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() frame decode error=2
07-04 15:26:10.850  29459-30445/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() first frame cannot be decoded - trying to sync again
07-04 15:26:10.850  29459-30445/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() cannot re-sync the stream after next 752 bytes, status=12
07-04 15:26:10.850  29459-30445/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() frame decode error=2
07-04 15:26:10.850  29459-30445/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() first frame cannot be decoded - trying to sync again
07-04 15:26:10.850  29459-30445/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() cannot re-sync the stream after next 376 bytes, status=12
07-04 15:26:10.850  29459-30445/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() frame decode error=12
07-04 15:26:10.850  29459-30445/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() first frame cannot be decoded - trying to sync again
07-04 15:26:10.850  29459-30445/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() cannot re-sync the stream after next 188 bytes, status=12
07-04 15:26:10.850  29459-30445/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() frame decode error=12
07-04 15:26:10.850  29459-30445/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() first frame cannot be decoded - trying to sync again
07-04 15:26:10.850  29459-30445/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() cannot re-sync the stream after next 94 bytes, status=12
07-04 15:26:10.850  29459-30445/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() frame decode error=12
07-04 15:26:10.850  29459-30445/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() first frame cannot be decoded - trying to sync again
07-04 15:26:10.850  29459-30445/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() cannot re-sync the stream after next 47 bytes, status=12
07-04 15:26:10.850  29459-30445/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() init failed status=12
07-04 15:26:10.850  29459-30445/com.valueeducation E/Decoder﹕ start() failed err=-1
07-04 15:26:10.952  29459-30445/com.valueeducation E/AACPlayer﹕ playAsync():
    java.lang.RuntimeException: Cannot start native decoder
            at com.spoledge.aacdecoder.Decoder.start(Decoder.java:238)
            at com.spoledge.aacdecoder.AACPlayer.playImpl(AACPlayer.java:424)
            at com.spoledge.aacdecoder.AACPlayer.play(AACPlayer.java:386)
            at com.spoledge.aacdecoder.AACPlayer.play(AACPlayer.java:338)
            at com.spoledge.aacdecoder.AACPlayer$1.run(AACPlayer.java:296)
            at java.lang.Thread.run(Thread.java:818)
07-04 15:26:25.900  29459-30507/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() frame decode error=1
07-04 15:26:25.900  29459-30507/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() first frame cannot be decoded - trying to sync again
07-04 15:26:25.900  29459-30507/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() frame decode error=2
07-04 15:26:25.900  29459-30507/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() first frame cannot be decoded - trying to sync again
07-04 15:26:25.900  29459-30507/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() cannot re-sync the stream after next 752 bytes, status=12
07-04 15:26:25.900  29459-30507/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() frame decode error=2
07-04 15:26:25.900  29459-30507/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() first frame cannot be decoded - trying to sync again
07-04 15:26:25.900  29459-30507/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() cannot re-sync the stream after next 376 bytes, status=12
07-04 15:26:25.900  29459-30507/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() frame decode error=12
07-04 15:26:25.900  29459-30507/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() first frame cannot be decoded - trying to sync again
07-04 15:26:25.900  29459-30507/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() cannot re-sync the stream after next 188 bytes, status=12
07-04 15:26:25.900  29459-30507/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() frame decode error=12
07-04 15:26:25.900  29459-30507/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() first frame cannot be decoded - trying to sync again
07-04 15:26:25.900  29459-30507/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() cannot re-sync the stream after next 94 bytes, status=12
07-04 15:26:25.900  29459-30507/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() frame decode error=12
07-04 15:26:25.900  29459-30507/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() first frame cannot be decoded - trying to sync again
07-04 15:26:25.900  29459-30507/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() cannot re-sync the stream after next 47 bytes, status=12
07-04 15:26:25.900  29459-30507/com.valueeducation E/Decoder[OpenCORE-MP3]﹕ start() init failed status=12
07-04 15:26:25.900  29459-30507/com.valueeducation E/Decoder﹕ start() failed err=-1
07-04 15:26:26.002  29459-30507/com.valueeducation E/AACPlayer﹕ playAsync():
    java.lang.RuntimeException: Cannot start native decoder
            at com.spoledge.aacdecoder.Decoder.start(Decoder.java:238)
            at com.spoledge.aacdecoder.AACPlayer.playImpl(AACPlayer.java:424)
            at com.spoledge.aacdecoder.AACPlayer.play(AACPlayer.java:386)
            at com.spoledge.aacdecoder.AACPlayer.play(AACPlayer.java:338)
            at com.spoledge.aacdecoder.AACPlayer$1.run(AACPlayer.java:296)
            at java.lang.Thread.run(Thread.java:818)

**Comment by cinder92** [comment]
+1 its because this plugin does not support all streaming formats :/
