### ISSUE TITLE
Not working in android

### ISSUE THREAD

**Issue by jose920405** [tlenclos/react-native-audio-streaming#110]
Works perfect for `IOS` but in android show the next error:

```
E/Decoder[OpenCORE-MP3]: start() frame decode error=12
E/Decoder[OpenCORE-MP3]: start() first frame cannot be decoded - trying to sync again
E/Decoder[OpenCORE-MP3]: start() cannot re-sync the stream after next 1024 bytes, status=12
E/Decoder[OpenCORE-MP3]: start() frame decode error=12
E/Decoder[OpenCORE-MP3]: start() first frame cannot be decoded - trying to sync again
E/Decoder[OpenCORE-MP3]: start() cannot re-sync the stream after next 1024 bytes, status=12
E/Decoder[OpenCORE-MP3]: start() frame decode error=12
E/Decoder[OpenCORE-MP3]: start() first frame cannot be decoded - trying to sync again
E/Decoder[OpenCORE-MP3]: start() frame decode error=12
E/Decoder[OpenCORE-MP3]: start() first frame cannot be decoded - trying to sync again
E/Decoder[OpenCORE-MP3]: start() cannot re-sync the stream after next 1024 bytes, status=12
E/Decoder[OpenCORE-MP3]: start() cannot re-sync the stream after next 1024 bytes, status=12
E/Decoder[OpenCORE-MP3]: start() frame decode error=12
E/Decoder[OpenCORE-MP3]: start() frame decode error=12
E/Decoder[OpenCORE-MP3]: start() first frame cannot be decoded - trying to sync again
E/Decoder[OpenCORE-MP3]: start() first frame cannot be decoded - trying to sync again
E/Decoder[OpenCORE-MP3]: start() cannot re-sync the stream after next 1024 bytes, status=12
E/Decoder[OpenCORE-MP3]: start() frame decode error=12
E/Decoder[OpenCORE-MP3]: start() first frame cannot be decoded - trying to sync again
E/Decoder[OpenCORE-MP3]: start() cannot re-sync the stream after next 1024 bytes, status=12
E/Decoder[OpenCORE-MP3]: start() cannot re-sync the stream after next 752 bytes, status=12
E/Decoder[OpenCORE-MP3]: start() frame decode error=12
E/Decoder[OpenCORE-MP3]: start() first frame cannot be decoded - trying to sync again
E/Decoder[OpenCORE-MP3]: start() cannot re-sync the stream after next 376 bytes, status=12
E/Decoder[OpenCORE-MP3]: start() frame decode error=12
E/Decoder[OpenCORE-MP3]: start() frame decode error=12
E/Decoder[OpenCORE-MP3]: start() first frame cannot be decoded - trying to sync again
E/Decoder[OpenCORE-MP3]: start() first frame cannot be decoded - trying to sync again
E/Decoder[OpenCORE-MP3]: start() cannot re-sync the stream after next 188 bytes, status=12
E/Decoder[OpenCORE-MP3]: start() frame decode error=12
E/Decoder[OpenCORE-MP3]: start() first frame cannot be decoded - trying to sync again
E/Decoder[OpenCORE-MP3]: start() cannot re-sync the stream after next 94 bytes, status=12
E/Decoder[OpenCORE-MP3]: start() frame decode error=12
E/Decoder[OpenCORE-MP3]: start() first frame cannot be decoded - trying to sync again
E/Decoder[OpenCORE-MP3]: start() cannot re-sync the stream after next 47 bytes, status=12
E/Decoder[OpenCORE-MP3]: start() init failed status=12
E/Decoder: start() failed err=-1
E/Decoder[OpenCORE-MP3]: start() cannot re-sync the stream after next 1024 bytes, status=12
E/Decoder[OpenCORE-MP3]: start() frame decode error=12
E/Decoder[OpenCORE-MP3]: start() first frame cannot be decoded - trying to sync again
E/Decoder[OpenCORE-MP3]: start() cannot re-sync the stream after next 1024 bytes, status=12
E/Decoder[OpenCORE-MP3]: start() frame decode error=12
E/Decoder[OpenCORE-MP3]: start() first frame cannot be decoded - trying to sync again
E/Decoder[OpenCORE-MP3]: start() cannot re-sync the stream after next 752 bytes, status=12
E/Decoder[OpenCORE-MP3]: start() frame decode error=12
E/Decoder[OpenCORE-MP3]: start() first frame cannot be decoded - trying to sync again
E/Decoder[OpenCORE-MP3]: start() cannot re-sync the stream after next 376 bytes, status=12
E/Decoder[OpenCORE-MP3]: start() frame decode error=12
E/Decoder[OpenCORE-MP3]: start() first frame cannot be decoded - trying to sync again
E/Decoder[OpenCORE-MP3]: start() cannot re-sync the stream after next 188 bytes, status=12
E/Decoder[OpenCORE-MP3]: start() frame decode error=12
E/Decoder[OpenCORE-MP3]: start() first frame cannot be decoded - trying to sync again
E/Decoder[OpenCORE-MP3]: start() cannot re-sync the stream after next 94 bytes, status=12
E/Decoder[OpenCORE-MP3]: start() frame decode error=12
E/Decoder[OpenCORE-MP3]: start() first frame cannot be decoded - trying to sync again
E/Decoder[OpenCORE-MP3]: start() cannot re-sync the stream after next 47 bytes, status=12
E/Decoder[OpenCORE-MP3]: start() init failed status=12
E/Decoder: start() failed err=-1
E/AACPlayer: playAsync():
                   java.lang.RuntimeException: Cannot start native decoder
                       at com.spoledge.aacdecoder.Decoder.start(Decoder.java:238)
                       at com.spoledge.aacdecoder.AACPlayer.playImpl(AACPlayer.java:424)
                       at com.spoledge.aacdecoder.AACPlayer.play(AACPlayer.java:386)
                       at com.spoledge.aacdecoder.AACPlayer.play(AACPlayer.java:338)
                       at com.spoledge.aacdecoder.AACPlayer$1.run(AACPlayer.java:296)
                       at java.lang.Thread.run(Thread.java:831)
E/AACPlayer: playAsync():
                   java.lang.RuntimeException: Cannot start native decoder
                       at com.spoledge.aacdecoder.Decoder.start(Decoder.java:238)
                       at com.spoledge.aacdecoder.AACPlayer.playImpl(AACPlayer.java:424)
                       at com.spoledge.aacdecoder.AACPlayer.play(AACPlayer.java:386)
                       at com.spoledge.aacdecoder.AACPlayer.play(AACPlayer.java:338)
                       at com.spoledge.aacdecoder.AACPlayer$1.run(AACPlayer.java:296)
                       at java.lang.Thread.run(Thread.java:831)

```

**Comment by jose920405** [comment]
Can someone please help me with this?

**Comment by lillogoal** [comment]
I have the same problem
