### ISSUE TITLE
App crashes on Android when Notifications set to false

### ISSUE THREAD

**Issue by damusnet** [tlenclos/react-native-audio-streaming#33]
Everything seems to work fine with Notifications enabled, but as soon as I turn them off, the app crashes on `play()`. Here is the error log:

```
             --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: Thread-189
  Process: com.girondins, PID: 2705
  java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.RemoteViews.setTextViewText(int, java.lang.CharSequence)' on a null object reference
    at com.audioStreaming.Signal.playerMetadata(Signal.java:333)
    at com.spoledge.aacdecoder.IcyInputStream.parseMetadata(IcyInputStream.java:231)
    at com.spoledge.aacdecoder.IcyInputStream.fetchMetadata(IcyInputStream.java:205)
    at com.spoledge.aacdecoder.IcyInputStream.read(IcyInputStream.java:133)
    at com.spoledge.aacdecoder.BufferReader.run(BufferReader.java:155)
    at java.lang.Thread.run(Thread.java:818)
```

I did a simple `ReactNativeAudioStreaming.play(url, { showIniOSMediaCenter: true, showInAndroidNotifications: false });`

**Comment by tlenclos** [comment]
Fixed with https://github.com/tlenclos/react-native-audio-streaming/pull/75.
