### ISSUE TITLE
[Android] ReactNativeAudioStreamingModule.getClassActivity null pointer exception

### ISSUE THREAD

**Issue by damusnet** [tlenclos/react-native-audio-streaming#51]
Hi,

I'm getting the following crash reports from Fabric Crashlytics on Android (version 4.x.x, 5.x.x & 6.x.x) with `react-native-audio-streaming@2.3.0`:

```
Fatal Exception: java.lang.NullPointerException
       at com.audioStreaming.ReactNativeAudioStreamingModule.getClassActivity(ReactNativeAudioStreamingModule.java:43)
       at com.audioStreaming.Signal.setData(Signal.java:66)
       at com.audioStreaming.ReactNativeAudioStreamingModule.onServiceConnected(ReactNativeAudioStreamingModule.java:78)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1140)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1157)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5315)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Haven't been able to reproduce myself, but 6 users on different phones already had it.
Unfortunately I don't know enough java to submit a PR.

**Comment by tlenclos** [comment]
Closing in favor of https://github.com/tlenclos/react-native-audio-streaming/issues/53.
