### ISSUE TITLE
android - Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference

### ISSUE THREAD

**Issue by psyzz** [tlenclos/react-native-audio-streaming#53]
Hello guys,

i'm trying to build an app i made on iOS to Android, and i have this error at startup:

```
12-13 17:18:36.483  5384  5384 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
12-13 17:18:36.483  5384  5384 E AndroidRuntime: 	at com.audioStreaming.ReactNativeAudioStreamingModule.getClassActivity(ReactNativeAudioStreamingModule.java:43)
12-13 17:18:36.483  5384  5384 E AndroidRuntime: 	at com.audioStreaming.Signal.setData(Signal.java:66)
12-13 17:18:36.483  5384  5384 E AndroidRuntime: 	at com.audioStreaming.ReactNativeAudioStreamingModule.onServiceConnected(ReactNativeAudioStreamingModule.java:78)
12-13 17:18:36.483  5384  5384 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1223)
12-13 17:18:36.483  5384  5384 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1240)
12-13 17:18:36.483  5384  5384 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
12-13 17:18:36.483  5384  5384 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-13 17:18:36.483  5384  5384 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
12-13 17:18:36.483  5384  5384 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
12-13 17:18:36.483  5384  5384 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-13 17:18:36.483  5384  5384 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
12-13 17:18:36.483  5384  5384 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
12-13 17:18:36.484   816  2166 W ActivityManager:   Force finishing activity com.app/.MainActivity
```

Do you have any idea?
Thanks!

"react-native-audio-streaming": "^2.2.0",
"react-native": "0.35.0",
"react": "15.3.2"

My MainApplication.java:

```
package com.app;

import android.app.Application;
import android.support.annotation.NonNull;
import android.util.Log;

import com.facebook.react.ReactApplication;
import com.reactnativenavigation.NavigationApplication;
import com.wog.videoplayer.VideoPlayerPackage;
import com.cmcewen.blurview.BlurViewPackage;
import com.audioStreaming.ReactNativeAudioStreamingPackage;
import com.rnim.rn.audio.ReactNativeAudioPackage;
import com.brentvatne.react.ReactVideoPackage;
import fr.bamlab.rnimageresizer.ImageResizerPackage;
import com.reactnative.ivpusic.imagepicker.PickerPackage;
import com.microsoft.codepush.react.CodePush;
import com.geektime.reactnativeonesignal.ReactNativeOneSignalPackage;
import com.imagepicker.ImagePickerPackage;
import com.RNFetchBlob.RNFetchBlobPackage;
import com.oblador.vectoricons.VectorIconsPackage;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends NavigationApplication {

  @Override
  public boolean isDebug() {
      return BuildConfig.DEBUG;
  }

  @NonNull
  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
      return Arrays.<ReactPackage>asList(
          new VideoPlayerPackage(),
          new BlurViewPackage(),
          new ReactNativeAudioStreamingPackage(),
          new ReactNativeAudioPackage(),
          new ReactVideoPackage(),
          new ImageResizerPackage(),
          new PickerPackage(),
          new CodePush(null, getApplicationContext(), BuildConfig.DEBUG),
          new ReactNativeOneSignalPackage(),
          new ImagePickerPackage(),
          new RNFetchBlobPackage(),
          new VectorIconsPackage()
      );
  }
}
```

**Comment by Arkanine** [comment]
Hi, I have the same issue.

**Comment by arshavinho** [comment]
Couldn't find a fix yet :(

**Comment by tlenclos** [comment]
Will look into it this weekend. Do you experience this bug when only including this module ?

**Comment by arshavinho** [comment]
Yes, i can't run my app with it, i need to remove ReactNativeAudioStreamingPackage() from MainApplication.java and all related code in android/settings.gradle and android/app/build.gradle

**Comment by Arkanine** [comment]
In my case react-native-audio-streaming module crash the process of react-native-push-notification when i receive remote notification and the app are closed.

**Comment by Arkanine** [comment]
@arshavinho try to set new ReactNativeAudioStreamingPackage() into MainApplication.java
instead of new ReactNativeAudioStreamingPackage(MainActivity.class).

**Comment by tlenclos** [comment]
I can't manage to reproduce the error but it seems that for some reason the currentActivity could be null in the module. I found some workaround here https://github.com/bourgois/react-native-hockeyapp/commit/224a4472cae41777a23c928821ace169f3a34e97 and in the react-native doc http://facebook.github.io/react-native/docs/native-modules-android.html#getting-activity-result-from-startactivityforresult.

If someone want to take a look, or give me access to a public repo with the bug, I could look into it.

**Comment by arshavinho** [comment]
@Arkanine i already have new ReactNativeAudioStreamingPackage(); in my MainApplication.java
@tlenclos thanks for your time, when i open my project in Android Studio i have this:
![screen shot 2016-12-19 at 01 35 13](https://cloud.githubusercontent.com/assets/1016441/21298122/70817194-c58c-11e6-8854-a04b064ed688.png)

and in ReactNativeAudioStreamingModule.java:
![screen shot 2016-12-19 at 01 41 24](https://cloud.githubusercontent.com/assets/1016441/21298131/8c3014ae-c58c-11e6-94e2-270c23ab7a66.png)

Maybe it's related to react-native-navigation ? For android we need to change or MainApplication.java and MainActivity:

https://github.com/wix/react-native-navigation/wiki/Installation---Android

**Comment by arshavinho** [comment]
i modified ReactNativeAudioStreamingModule.java like:

````
import android.app.Activity;
.
.
.
public Class<?> getClassActivity() {
    Activity currentActivity = getCurrentActivity();
    if (currentActivity == null) {
        // The currentActivity can be null if it is backgrounded / destroyed, so we simply
        // no-op to prevent any null pointer exceptions.
        return null;
    }
    if (this.clsActivity == null) {
      this.clsActivity = getCurrentActivity().getClass();
    }
    return this.clsActivity;
  }
```
and now the app starts, but when i try to play a sound i get:

```
12-18 20:13:05.077 11308 11396 E unknown:React: Exception in native call
12-18 20:13:05.077 11308 11396 E unknown:React: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
12-18 20:13:05.077 11308 11396 E unknown:React: 	at android.content.ComponentName.<init>(ComponentName.java:129)
12-18 20:13:05.077 11308 11396 E unknown:React: 	at android.content.Intent.<init>(Intent.java:4449)
12-18 20:13:05.077 11308 11396 E unknown:React: 	at com.audioStreaming.Signal.showNotification(Signal.java:175)
12-18 20:13:05.077 11308 11396 E unknown:React: 	at com.audioStreaming.ReactNativeAudioStreamingModule.playInternal(ReactNativeAudioStreamingModule.java:105)
12-18 20:13:05.077 11308 11396 E unknown:React: 	at com.audioStreaming.ReactNativeAudioStreamingModule.play(ReactNativeAudioStreamingModule.java:99)
12-18 20:13:05.077 11308 11396 E unknown:React: 	at java.lang.reflect.Method.invoke(Native Method)
12-18 20:13:05.077 11308 11396 E unknown:React: 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
12-18 20:13:05.077 11308 11396 E unknown:React: 	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
12-18 20:13:05.077 11308 11396 E unknown:React: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
12-18 20:13:05.077 11308 11396 E unknown:React: 	at android.os.Handler.handleCallback(Handler.java:739)
12-18 20:13:05.077 11308 11396 E unknown:React: 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-18 20:13:05.077 11308 11396 E unknown:React: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
12-18 20:13:05.077 11308 11396 E unknown:React: 	at android.os.Looper.loop(Looper.java:148)
12-18 20:13:05.077 11308 11396 E unknown:React: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
12-18 20:13:05.077 11308 11396 E unknown:React: 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by hugohow** [comment]
I have the same bug :/

**Comment by arshavinho** [comment]
unfortunately no :(

**Comment by marcshilling** [comment]
Adding `<service android:name=".ReactNativeAudioStreaming.Signal" android:enabled="true" />` to my manifest file fixed this issue.

**Comment by lucasromanojf** [comment]
I still have the same issue.

**Comment by cherniv** [comment]
Are you using code-push? Cause in my case this is what causes this bug

**Comment by psyzz** [comment]
@cherniv yes using codepush

**Comment by cherniv** [comment]
I've opened an issue: https://github.com/Microsoft/react-native-code-push/issues/872 , but it looks like no one can help, frustrating...

**Comment by SydneyTR** [comment]
Still an issue

**Comment by arcollector** [comment]
add these lines to `Signal.java`

```java
public void showNotification() {
        if(clsActivity == null) {
            clsActivity = module.getClassActivity();
        }
        ....
```
