### ISSUE TITLE
m4a playing fails on android

### ISSUE THREAD

**Issue by djohnkirby** [tlenclos/react-native-audio-streaming#70]
This is occurring both in my app and in the example app for me. When I try to play any m4a stream it fails with:

E/AACPlayer: playAsync():
                                                        java.lang.RuntimeException: Cannot start native decoder
                                                            at com.spoledge.aacdecoder.Decoder.start(Decoder.java:238)
                                                            at com.spoledge.aacdecoder.AACPlayer.playImpl(AACPlayer.java:424)
                                                            at com.spoledge.aacdecoder.AACPlayer.play(AACPlayer.java:386)
                                                            at com.spoledge.aacdecoder.AACPlayer.play(AACPlayer.java:338)
                                                            at com.spoledge.aacdecoder.AACPlayer$1.run(AACPlayer.java:296)
                                                            at java.lang.Thread.run(Thread.java:761)

**Comment by jsaucedo** [comment]
hi! Did you solve this problem? I'm facing it too

**Comment by medlmichael** [comment]
Looks like I'm getting a similar issue as well.  Any thoughts?

**Comment by cherniv** [comment]
+1

**Comment by davidnoguerol** [comment]
+1000  it's the format for Podcast audio files (which is a trendy thing),

**Comment by gHashTag** [comment]
+1

**Comment by jose920405** [comment]
it's happening to me with `.mp3` files format
